// fields/shared/units.ts
export const Units = ['gr', 'g', 'oz', 'ea', 'lbs', 'kg', 'ml', 'l', 'tsp', 'gal', 'tbsp', 'cup', 'pcs', 'pc', 'qt','tt','bag','case','box','portion','hotel pan','order','pastry bags', 'hp', 'block'];
  
// fields/shared/allergens.ts
export const Allergens = [
    { "label": "Alcohol", "value": "alcohol" },
    { "label": "Allium", "value": "allium" },
    { "label": "Anchovy", "value": "anchovy" },
    { "label": "Ancient Grains", "value": "ancient_grains" },
    { "label": "Black Pepper", "value": "black_pepper" },
    { "label": "Capsaicin", "value": "capsaicin" },
    { "label": "Cilantro", "value": "cilantro" },
    { "label": "Cinnamon", "value": "cinnamon" },
    { "label": "Citrus", "value": "citrus" },
    { "label": "Dairy", "value": "dairy" },
    { "label": "Eggs", "value": "eggs" },
    { "label": "Fin Fish", "value": "fin_fish" },
    { "label": "Fish", "value": "fish" },
    { "label": "Fish Roe", "value": "fish_roe" },
    { "label": "Fryer Cross Contact", "value": "fryer_cc_issues" },
    { "label": "Garlic", "value": "garlic" },
    { "label": "Ginger", "value": "ginger" },
    { "label": "Gluten", "value": "gluten" },
    { "label": "Honey", "value": "honey" },
    { "label": "Legumes", "value": "legumes" },
    { "label": "MSG", "value": "msg" },
    { "label": "Mollusk", "value": "mollusk" },
    { "label": "Mushroom", "value": "mushroom" },
    { "label": "Mustard", "value": "mustard" },
    { "label": "Nightshade", "value": "nightshade" },
    { "label": "Onion", "value": "onion" },
    { "label": "Peanuts", "value": "peanuts" },
    { "label": "Pineapple", "value": "pineapple" },
    { "label": "Pork", "value": "pork" },
    { "label": "Seafood", "value": "seafood" },
    { "label": "Sesame", "value": "sesame" },
    { "label": "Shellfish", "value": "shellfish" },
    { "label": "Soy", "value": "soy" },
    { "label": "Stonefruit", "value": "stonefruit" },
    { "label": "Sulfites", "value": "sulfites" },
    { "label": "Tree Nuts", "value": "tree_nuts" },
    { "label": "Wheat", "value": "wheat" },
    { "label": "Yeast", "value": "yeast" }
];