/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:db-schema` to regenerate this file.
 */

import type {} from '@payloadcms/db-postgres'
import {
  pgTable,
  index,
  uniqueIndex,
  foreignKey,
  serial,
  timestamp,
  varchar,
  numeric,
  integer,
  boolean,
  jsonb,
  pgEnum,
} from '@payloadcms/db-postgres/drizzle/pg-core'
import { sql, relations } from '@payloadcms/db-postgres/drizzle'
export const enum_app_users_role = pgEnum('enum_app_users_role', [
  'foh',
  'boh',
  'bartender',
  'admin',
])
export const enum_recipes_ingredients_unit = pgEnum('enum_recipes_ingredients_unit', [
  'gr',
  'g',
  'oz',
  'ea',
  'lbs',
  'kg',
  'ml',
  'l',
  'tsp',
  'gal',
  'tbsp',
  'cup',
  'pcs',
  'pc',
  'qt',
  'tt',
  'bag',
  'case',
  'box',
  'portion',
  'hotel pan',
  'order',
  'pastry bags',
  'hp',
  'block',
])
export const enum_recipes_category = pgEnum('enum_recipes_category', ['', 'dinner', 'brunch'])
export const enum_recipes_allergens = pgEnum('enum_recipes_allergens', [
  'alcohol',
  'allium',
  'anchovy',
  'ancient_grains',
  'black_pepper',
  'capsaicin',
  'cilantro',
  'cinnamon',
  'citrus',
  'dairy',
  'eggs',
  'fish',
  'fish_roe',
  'fryer_cc_issues',
  'garlic',
  'ginger',
  'gluten',
  'honey',
  'msg',
  'mollusk',
  'mushroom',
  'mustard',
  'nightshade',
  'onion',
  'peanuts',
  'pineapple',
  'pork',
  'seafood',
  'sesame',
  'shellfish',
  'soy',
  'stonefruit',
  'sulfites',
  'tree_nuts',
  'wheat',
])
export const enum_recipes_prep_ingredients_unit = pgEnum('enum_recipes_prep_ingredients_unit', [
  'gr',
  'g',
  'oz',
  'ea',
  'lbs',
  'kg',
  'ml',
  'l',
  'tsp',
  'gal',
  'tbsp',
  'cup',
  'pcs',
  'pc',
  'qt',
  'tt',
  'bag',
  'case',
  'box',
  'portion',
  'hotel pan',
  'order',
  'pastry bags',
  'hp',
  'block',
])
export const enum_recipes_prep_category = pgEnum('enum_recipes_prep_category', [
  '',
  'dinner',
  'brunch',
])
export const enum_recipes_prep_allergens = pgEnum('enum_recipes_prep_allergens', [
  'alcohol',
  'allium',
  'anchovy',
  'ancient_grains',
  'black_pepper',
  'capsaicin',
  'cilantro',
  'cinnamon',
  'citrus',
  'dairy',
  'eggs',
  'fish',
  'fish_roe',
  'fryer_cc_issues',
  'garlic',
  'ginger',
  'gluten',
  'honey',
  'msg',
  'mollusk',
  'mushroom',
  'mustard',
  'nightshade',
  'onion',
  'peanuts',
  'pineapple',
  'pork',
  'seafood',
  'sesame',
  'shellfish',
  'soy',
  'stonefruit',
  'sulfites',
  'tree_nuts',
  'wheat',
])
export const enum_recipes_prep_total_yield_unit = pgEnum('enum_recipes_prep_total_yield_unit', [
  'gr',
  'g',
  'oz',
  'ea',
  'lbs',
  'kg',
  'ml',
  'l',
  'tsp',
  'gal',
  'tbsp',
  'cup',
  'pcs',
  'pc',
  'qt',
  'tt',
  'bag',
  'case',
  'box',
  'portion',
  'hotel pan',
  'order',
  'pastry bags',
  'hp',
  'block',
])
export const enum_cocktail_recipes_ingredients_unit = pgEnum(
  'enum_cocktail_recipes_ingredients_unit',
  ['', 'oz', 'ml', 'dash', 'tsp', 'tbsp', 'g', 'drop', 'splash', 'ea'],
)
export const enum_cocktail_recipes_ingredients_full_unit = pgEnum(
  'enum_cocktail_recipes_ingredients_full_unit',
  ['', 'oz', 'ml', 'dash', 'tsp', 'tbsp', 'g', 'drop', 'splash', 'ea'],
)
export const enum_cocktail_prep_items_ingredients_unit = pgEnum(
  'enum_cocktail_prep_items_ingredients_unit',
  ['g', 'kg', 'ml', 'l', 'tsp', 'tbsp', 'cup', 'pcs', 'ea', 'quart'],
)
export const enum_cocktail_batch_recipes_ingredients_unit = pgEnum(
  'enum_cocktail_batch_recipes_ingredients_unit',
  ['g', 'kg', 'ml', 'l', 'tsp', 'tbsp', 'cup', 'pcs', 'ea'],
)

export const users = pgTable(
  'users',
  {
    id: serial('id').primaryKey(),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    email: varchar('email').notNull(),
    resetPasswordToken: varchar('reset_password_token'),
    resetPasswordExpiration: timestamp('reset_password_expiration', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    salt: varchar('salt'),
    hash: varchar('hash'),
    loginAttempts: numeric('login_attempts').default('0'),
    lockUntil: timestamp('lock_until', { mode: 'string', withTimezone: true, precision: 3 }),
  },
  (columns) => ({
    users_updated_at_idx: index('users_updated_at_idx').on(columns.updatedAt),
    users_created_at_idx: index('users_created_at_idx').on(columns.createdAt),
    users_email_idx: uniqueIndex('users_email_idx').on(columns.email),
  }),
)

export const app_users_role = pgTable(
  'app_users_role',
  {
    order: integer('order').notNull(),
    parent: integer('parent_id').notNull(),
    value: enum_app_users_role('value'),
    id: serial('id').primaryKey(),
  },
  (columns) => ({
    orderIdx: index('app_users_role_order_idx').on(columns.order),
    parentIdx: index('app_users_role_parent_idx').on(columns.parent),
    parentFk: foreignKey({
      columns: [columns['parent']],
      foreignColumns: [app_users.id],
      name: 'app_users_role_parent_fk',
    }).onDelete('cascade'),
  }),
)

export const app_users = pgTable(
  'app_users',
  {
    id: serial('id').primaryKey(),
    name: varchar('name').notNull(),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    email: varchar('email').notNull(),
    resetPasswordToken: varchar('reset_password_token'),
    resetPasswordExpiration: timestamp('reset_password_expiration', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    salt: varchar('salt'),
    hash: varchar('hash'),
    loginAttempts: numeric('login_attempts').default('0'),
    lockUntil: timestamp('lock_until', { mode: 'string', withTimezone: true, precision: 3 }),
  },
  (columns) => ({
    app_users_updated_at_idx: index('app_users_updated_at_idx').on(columns.updatedAt),
    app_users_created_at_idx: index('app_users_created_at_idx').on(columns.createdAt),
    app_users_email_idx: uniqueIndex('app_users_email_idx').on(columns.email),
  }),
)

export const media = pgTable(
  'media',
  {
    id: serial('id').primaryKey(),
    alt: varchar('alt'),
    prefix: varchar('prefix').default('media'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    url: varchar('url'),
    thumbnailURL: varchar('thumbnail_u_r_l'),
    filename: varchar('filename'),
    mimeType: varchar('mime_type'),
    filesize: numeric('filesize'),
    width: numeric('width'),
    height: numeric('height'),
    focalX: numeric('focal_x'),
    focalY: numeric('focal_y'),
  },
  (columns) => ({
    media_updated_at_idx: index('media_updated_at_idx').on(columns.updatedAt),
    media_created_at_idx: index('media_created_at_idx').on(columns.createdAt),
    media_filename_idx: uniqueIndex('media_filename_idx').on(columns.filename),
  }),
)

export const recipes_ingredients = pgTable(
  'recipes_ingredients',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    ingredient: varchar('ingredient').notNull(),
    unit: enum_recipes_ingredients_unit('unit').notNull(),
    qty: numeric('qty'),
    'cuts-prep-brand': varchar('cuts_prep_brand'),
    isSubRecipe: boolean('is_sub_recipe').default(false),
    linkedRecipe: integer('linked_recipe_id').references(() => recipes_prep.id, {
      onDelete: 'set null',
    }),
  },
  (columns) => ({
    _orderIdx: index('recipes_ingredients_order_idx').on(columns._order),
    _parentIDIdx: index('recipes_ingredients_parent_id_idx').on(columns._parentID),
    recipes_ingredients_linked_recipe_idx: index('recipes_ingredients_linked_recipe_idx').on(
      columns.linkedRecipe,
    ),
    _parentIDFk: foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [recipes.id],
      name: 'recipes_ingredients_parent_id_fk',
    }).onDelete('cascade'),
  }),
)

export const recipes_category = pgTable(
  'recipes_category',
  {
    order: integer('order').notNull(),
    parent: integer('parent_id').notNull(),
    value: enum_recipes_category('value'),
    id: serial('id').primaryKey(),
  },
  (columns) => ({
    orderIdx: index('recipes_category_order_idx').on(columns.order),
    parentIdx: index('recipes_category_parent_idx').on(columns.parent),
    parentFk: foreignKey({
      columns: [columns['parent']],
      foreignColumns: [recipes.id],
      name: 'recipes_category_parent_fk',
    }).onDelete('cascade'),
  }),
)

export const recipes_allergens = pgTable(
  'recipes_allergens',
  {
    order: integer('order').notNull(),
    parent: integer('parent_id').notNull(),
    value: enum_recipes_allergens('value'),
    id: serial('id').primaryKey(),
  },
  (columns) => ({
    orderIdx: index('recipes_allergens_order_idx').on(columns.order),
    parentIdx: index('recipes_allergens_parent_idx').on(columns.parent),
    parentFk: foreignKey({
      columns: [columns['parent']],
      foreignColumns: [recipes.id],
      name: 'recipes_allergens_parent_fk',
    }).onDelete('cascade'),
  }),
)

export const recipes_images = pgTable(
  'recipes_images',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    image: integer('image_id')
      .notNull()
      .references(() => media.id, {
        onDelete: 'set null',
      }),
    caption: varchar('caption'),
  },
  (columns) => ({
    _orderIdx: index('recipes_images_order_idx').on(columns._order),
    _parentIDIdx: index('recipes_images_parent_id_idx').on(columns._parentID),
    recipes_images_image_idx: index('recipes_images_image_idx').on(columns.image),
    _parentIDFk: foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [recipes.id],
      name: 'recipes_images_parent_id_fk',
    }).onDelete('cascade'),
  }),
)

export const recipes = pgTable(
  'recipes',
  {
    id: serial('id').primaryKey(),
    name: varchar('name').notNull(),
    method: varchar('method'),
    plateBuild: varchar('plate_build'),
    implemented: varchar('implemented'),
    lastRevised: timestamp('last_revised', { mode: 'string', withTimezone: true, precision: 3 }),
    prepTime: varchar('prep_time'),
    kitchen: varchar('kitchen'),
    stations: varchar('stations'),
    mealPeriod: varchar('meal_period'),
    mealType: varchar('meal_type'),
    platingInstructions: varchar('plating_instructions'),
    plateType: varchar('plate_type'),
    utensils: varchar('utensils'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => ({
    recipes_name_idx: uniqueIndex('recipes_name_idx').on(columns.name),
    recipes_updated_at_idx: index('recipes_updated_at_idx').on(columns.updatedAt),
    recipes_created_at_idx: index('recipes_created_at_idx').on(columns.createdAt),
  }),
)

export const recipes_prep_ingredients = pgTable(
  'recipes_prep_ingredients',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    ingredient: varchar('ingredient').notNull(),
    unit: enum_recipes_prep_ingredients_unit('unit').notNull(),
    qty: numeric('qty'),
    'cuts-prep-brand': varchar('cuts_prep_brand'),
    isSubRecipe: boolean('is_sub_recipe').default(false),
    linkedRecipe: integer('linked_recipe_id').references(() => recipes_prep.id, {
      onDelete: 'set null',
    }),
  },
  (columns) => ({
    _orderIdx: index('recipes_prep_ingredients_order_idx').on(columns._order),
    _parentIDIdx: index('recipes_prep_ingredients_parent_id_idx').on(columns._parentID),
    recipes_prep_ingredients_linked_recipe_idx: index(
      'recipes_prep_ingredients_linked_recipe_idx',
    ).on(columns.linkedRecipe),
    _parentIDFk: foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [recipes_prep.id],
      name: 'recipes_prep_ingredients_parent_id_fk',
    }).onDelete('cascade'),
  }),
)

export const recipes_prep_category = pgTable(
  'recipes_prep_category',
  {
    order: integer('order').notNull(),
    parent: integer('parent_id').notNull(),
    value: enum_recipes_prep_category('value'),
    id: serial('id').primaryKey(),
  },
  (columns) => ({
    orderIdx: index('recipes_prep_category_order_idx').on(columns.order),
    parentIdx: index('recipes_prep_category_parent_idx').on(columns.parent),
    parentFk: foreignKey({
      columns: [columns['parent']],
      foreignColumns: [recipes_prep.id],
      name: 'recipes_prep_category_parent_fk',
    }).onDelete('cascade'),
  }),
)

export const recipes_prep_allergens = pgTable(
  'recipes_prep_allergens',
  {
    order: integer('order').notNull(),
    parent: integer('parent_id').notNull(),
    value: enum_recipes_prep_allergens('value'),
    id: serial('id').primaryKey(),
  },
  (columns) => ({
    orderIdx: index('recipes_prep_allergens_order_idx').on(columns.order),
    parentIdx: index('recipes_prep_allergens_parent_idx').on(columns.parent),
    parentFk: foreignKey({
      columns: [columns['parent']],
      foreignColumns: [recipes_prep.id],
      name: 'recipes_prep_allergens_parent_fk',
    }).onDelete('cascade'),
  }),
)

export const recipes_prep_images = pgTable(
  'recipes_prep_images',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    image: integer('image_id')
      .notNull()
      .references(() => media.id, {
        onDelete: 'set null',
      }),
    caption: varchar('caption'),
  },
  (columns) => ({
    _orderIdx: index('recipes_prep_images_order_idx').on(columns._order),
    _parentIDIdx: index('recipes_prep_images_parent_id_idx').on(columns._parentID),
    recipes_prep_images_image_idx: index('recipes_prep_images_image_idx').on(columns.image),
    _parentIDFk: foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [recipes_prep.id],
      name: 'recipes_prep_images_parent_id_fk',
    }).onDelete('cascade'),
  }),
)

export const recipes_prep = pgTable(
  'recipes_prep',
  {
    id: serial('id').primaryKey(),
    name: varchar('name').notNull(),
    dishes: varchar('dishes'),
    method: varchar('method'),
    prepTime: varchar('prep_time'),
    shelfLife: varchar('shelf_life'),
    stations: varchar('stations'),
    equipment: varchar('equipment'),
    kitchenTools: varchar('kitchen_tools'),
    totalYield_qty: numeric('total_yield_qty'),
    totalYield_unit: enum_recipes_prep_total_yield_unit('total_yield_unit'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => ({
    recipes_prep_name_idx: uniqueIndex('recipes_prep_name_idx').on(columns.name),
    recipes_prep_updated_at_idx: index('recipes_prep_updated_at_idx').on(columns.updatedAt),
    recipes_prep_created_at_idx: index('recipes_prep_created_at_idx').on(columns.createdAt),
  }),
)

export const cocktail_recipes_ingredients = pgTable(
  'cocktail_recipes_ingredients',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    ingredient: varchar('ingredient').notNull(),
    unit: enum_cocktail_recipes_ingredients_unit('unit').notNull(),
    qty: numeric('qty').notNull(),
    isSubRecipe: boolean('is_sub_recipe').default(false),
  },
  (columns) => ({
    _orderIdx: index('cocktail_recipes_ingredients_order_idx').on(columns._order),
    _parentIDIdx: index('cocktail_recipes_ingredients_parent_id_idx').on(columns._parentID),
    _parentIDFk: foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [cocktail_recipes.id],
      name: 'cocktail_recipes_ingredients_parent_id_fk',
    }).onDelete('cascade'),
  }),
)

export const cocktail_recipes_ingredients_full = pgTable(
  'cocktail_recipes_ingredients_full',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    ingredient: varchar('ingredient').notNull(),
    unit: enum_cocktail_recipes_ingredients_full_unit('unit').notNull(),
    qty: numeric('qty').notNull(),
    isSubRecipe: boolean('is_sub_recipe').default(false),
  },
  (columns) => ({
    _orderIdx: index('cocktail_recipes_ingredients_full_order_idx').on(columns._order),
    _parentIDIdx: index('cocktail_recipes_ingredients_full_parent_id_idx').on(columns._parentID),
    _parentIDFk: foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [cocktail_recipes.id],
      name: 'cocktail_recipes_ingredients_full_parent_id_fk',
    }).onDelete('cascade'),
  }),
)

export const cocktail_recipes_images = pgTable(
  'cocktail_recipes_images',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    image: integer('image_id')
      .notNull()
      .references(() => media.id, {
        onDelete: 'set null',
      }),
    caption: varchar('caption'),
  },
  (columns) => ({
    _orderIdx: index('cocktail_recipes_images_order_idx').on(columns._order),
    _parentIDIdx: index('cocktail_recipes_images_parent_id_idx').on(columns._parentID),
    cocktail_recipes_images_image_idx: index('cocktail_recipes_images_image_idx').on(columns.image),
    _parentIDFk: foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [cocktail_recipes.id],
      name: 'cocktail_recipes_images_parent_id_fk',
    }).onDelete('cascade'),
  }),
)

export const cocktail_recipes = pgTable(
  'cocktail_recipes',
  {
    id: serial('id').primaryKey(),
    name: varchar('name').notNull(),
    method: varchar('method'),
    yield: varchar('yield'),
    ice: varchar('ice'),
    garnish: varchar('garnish'),
    glassware: varchar('glassware'),
    description: varchar('description'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => ({
    cocktail_recipes_updated_at_idx: index('cocktail_recipes_updated_at_idx').on(columns.updatedAt),
    cocktail_recipes_created_at_idx: index('cocktail_recipes_created_at_idx').on(columns.createdAt),
  }),
)

export const cocktail_recipes_rels = pgTable(
  'cocktail_recipes_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    'cocktail-prep-itemsID': integer('cocktail_prep_items_id'),
    'cocktail-batch-recipesID': integer('cocktail_batch_recipes_id'),
  },
  (columns) => ({
    order: index('cocktail_recipes_rels_order_idx').on(columns.order),
    parentIdx: index('cocktail_recipes_rels_parent_idx').on(columns.parent),
    pathIdx: index('cocktail_recipes_rels_path_idx').on(columns.path),
    cocktail_recipes_rels_cocktail_prep_items_id_idx: index(
      'cocktail_recipes_rels_cocktail_prep_items_id_idx',
    ).on(columns['cocktail-prep-itemsID']),
    cocktail_recipes_rels_cocktail_batch_recipes_id_idx: index(
      'cocktail_recipes_rels_cocktail_batch_recipes_id_idx',
    ).on(columns['cocktail-batch-recipesID']),
    parentFk: foreignKey({
      columns: [columns['parent']],
      foreignColumns: [cocktail_recipes.id],
      name: 'cocktail_recipes_rels_parent_fk',
    }).onDelete('cascade'),
    'cocktail-prep-itemsIdFk': foreignKey({
      columns: [columns['cocktail-prep-itemsID']],
      foreignColumns: [cocktail_prep_items.id],
      name: 'cocktail_recipes_rels_cocktail_prep_items_fk',
    }).onDelete('cascade'),
    'cocktail-batch-recipesIdFk': foreignKey({
      columns: [columns['cocktail-batch-recipesID']],
      foreignColumns: [cocktail_batch_recipes.id],
      name: 'cocktail_recipes_rels_cocktail_batch_recipes_fk',
    }).onDelete('cascade'),
  }),
)

export const cocktail_prep_items_ingredients = pgTable(
  'cocktail_prep_items_ingredients',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    ingredient: varchar('ingredient').notNull(),
    unit: enum_cocktail_prep_items_ingredients_unit('unit').notNull(),
    qty: numeric('qty').notNull(),
    isSubRecipe: boolean('is_sub_recipe').default(false),
    linkedRecipe: integer('linked_recipe_id').references(() => cocktail_prep_items.id, {
      onDelete: 'set null',
    }),
  },
  (columns) => ({
    _orderIdx: index('cocktail_prep_items_ingredients_order_idx').on(columns._order),
    _parentIDIdx: index('cocktail_prep_items_ingredients_parent_id_idx').on(columns._parentID),
    cocktail_prep_items_ingredients_linked_recipe_idx: index(
      'cocktail_prep_items_ingredients_linked_recipe_idx',
    ).on(columns.linkedRecipe),
    _parentIDFk: foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [cocktail_prep_items.id],
      name: 'cocktail_prep_items_ingredients_parent_id_fk',
    }).onDelete('cascade'),
  }),
)

export const cocktail_prep_items_images = pgTable(
  'cocktail_prep_items_images',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    image: integer('image_id')
      .notNull()
      .references(() => media.id, {
        onDelete: 'set null',
      }),
    caption: varchar('caption'),
  },
  (columns) => ({
    _orderIdx: index('cocktail_prep_items_images_order_idx').on(columns._order),
    _parentIDIdx: index('cocktail_prep_items_images_parent_id_idx').on(columns._parentID),
    cocktail_prep_items_images_image_idx: index('cocktail_prep_items_images_image_idx').on(
      columns.image,
    ),
    _parentIDFk: foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [cocktail_prep_items.id],
      name: 'cocktail_prep_items_images_parent_id_fk',
    }).onDelete('cascade'),
  }),
)

export const cocktail_prep_items = pgTable(
  'cocktail_prep_items',
  {
    id: serial('id').primaryKey(),
    name: varchar('name').notNull(),
    method: varchar('method'),
    yield: varchar('yield'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => ({
    cocktail_prep_items_updated_at_idx: index('cocktail_prep_items_updated_at_idx').on(
      columns.updatedAt,
    ),
    cocktail_prep_items_created_at_idx: index('cocktail_prep_items_created_at_idx').on(
      columns.createdAt,
    ),
  }),
)

export const cocktail_batch_recipes_ingredients = pgTable(
  'cocktail_batch_recipes_ingredients',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    ingredient: varchar('ingredient').notNull(),
    unit: enum_cocktail_batch_recipes_ingredients_unit('unit').notNull(),
    qty: numeric('qty').notNull(),
    isSubRecipe: boolean('is_sub_recipe').default(false),
    linkedRecipe: integer('linked_recipe_id').references(() => cocktail_prep_items.id, {
      onDelete: 'set null',
    }),
  },
  (columns) => ({
    _orderIdx: index('cocktail_batch_recipes_ingredients_order_idx').on(columns._order),
    _parentIDIdx: index('cocktail_batch_recipes_ingredients_parent_id_idx').on(columns._parentID),
    cocktail_batch_recipes_ingredients_linked_recipe_idx: index(
      'cocktail_batch_recipes_ingredients_linked_recipe_idx',
    ).on(columns.linkedRecipe),
    _parentIDFk: foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [cocktail_batch_recipes.id],
      name: 'cocktail_batch_recipes_ingredients_parent_id_fk',
    }).onDelete('cascade'),
  }),
)

export const cocktail_batch_recipes_images = pgTable(
  'cocktail_batch_recipes_images',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    image: integer('image_id')
      .notNull()
      .references(() => media.id, {
        onDelete: 'set null',
      }),
    caption: varchar('caption'),
  },
  (columns) => ({
    _orderIdx: index('cocktail_batch_recipes_images_order_idx').on(columns._order),
    _parentIDIdx: index('cocktail_batch_recipes_images_parent_id_idx').on(columns._parentID),
    cocktail_batch_recipes_images_image_idx: index('cocktail_batch_recipes_images_image_idx').on(
      columns.image,
    ),
    _parentIDFk: foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [cocktail_batch_recipes.id],
      name: 'cocktail_batch_recipes_images_parent_id_fk',
    }).onDelete('cascade'),
  }),
)

export const cocktail_batch_recipes = pgTable(
  'cocktail_batch_recipes',
  {
    id: serial('id').primaryKey(),
    name: varchar('name').notNull(),
    method: varchar('method'),
    yield: varchar('yield'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => ({
    cocktail_batch_recipes_updated_at_idx: index('cocktail_batch_recipes_updated_at_idx').on(
      columns.updatedAt,
    ),
    cocktail_batch_recipes_created_at_idx: index('cocktail_batch_recipes_created_at_idx').on(
      columns.createdAt,
    ),
  }),
)

export const payload_locked_documents = pgTable(
  'payload_locked_documents',
  {
    id: serial('id').primaryKey(),
    globalSlug: varchar('global_slug'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => ({
    payload_locked_documents_global_slug_idx: index('payload_locked_documents_global_slug_idx').on(
      columns.globalSlug,
    ),
    payload_locked_documents_updated_at_idx: index('payload_locked_documents_updated_at_idx').on(
      columns.updatedAt,
    ),
    payload_locked_documents_created_at_idx: index('payload_locked_documents_created_at_idx').on(
      columns.createdAt,
    ),
  }),
)

export const payload_locked_documents_rels = pgTable(
  'payload_locked_documents_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    usersID: integer('users_id'),
    appUsersID: integer('app_users_id'),
    mediaID: integer('media_id'),
    recipesID: integer('recipes_id'),
    'recipes-prepID': integer('recipes_prep_id'),
    'cocktail-recipesID': integer('cocktail_recipes_id'),
    'cocktail-prep-itemsID': integer('cocktail_prep_items_id'),
    'cocktail-batch-recipesID': integer('cocktail_batch_recipes_id'),
  },
  (columns) => ({
    order: index('payload_locked_documents_rels_order_idx').on(columns.order),
    parentIdx: index('payload_locked_documents_rels_parent_idx').on(columns.parent),
    pathIdx: index('payload_locked_documents_rels_path_idx').on(columns.path),
    payload_locked_documents_rels_users_id_idx: index(
      'payload_locked_documents_rels_users_id_idx',
    ).on(columns.usersID),
    payload_locked_documents_rels_app_users_id_idx: index(
      'payload_locked_documents_rels_app_users_id_idx',
    ).on(columns.appUsersID),
    payload_locked_documents_rels_media_id_idx: index(
      'payload_locked_documents_rels_media_id_idx',
    ).on(columns.mediaID),
    payload_locked_documents_rels_recipes_id_idx: index(
      'payload_locked_documents_rels_recipes_id_idx',
    ).on(columns.recipesID),
    payload_locked_documents_rels_recipes_prep_id_idx: index(
      'payload_locked_documents_rels_recipes_prep_id_idx',
    ).on(columns['recipes-prepID']),
    payload_locked_documents_rels_cocktail_recipes_id_idx: index(
      'payload_locked_documents_rels_cocktail_recipes_id_idx',
    ).on(columns['cocktail-recipesID']),
    payload_locked_documents_rels_cocktail_prep_items_id_idx: index(
      'payload_locked_documents_rels_cocktail_prep_items_id_idx',
    ).on(columns['cocktail-prep-itemsID']),
    payload_locked_documents_rels_cocktail_batch_recipes_id_idx: index(
      'payload_locked_documents_rels_cocktail_batch_recipes_id_idx',
    ).on(columns['cocktail-batch-recipesID']),
    parentFk: foreignKey({
      columns: [columns['parent']],
      foreignColumns: [payload_locked_documents.id],
      name: 'payload_locked_documents_rels_parent_fk',
    }).onDelete('cascade'),
    usersIdFk: foreignKey({
      columns: [columns['usersID']],
      foreignColumns: [users.id],
      name: 'payload_locked_documents_rels_users_fk',
    }).onDelete('cascade'),
    appUsersIdFk: foreignKey({
      columns: [columns['appUsersID']],
      foreignColumns: [app_users.id],
      name: 'payload_locked_documents_rels_app_users_fk',
    }).onDelete('cascade'),
    mediaIdFk: foreignKey({
      columns: [columns['mediaID']],
      foreignColumns: [media.id],
      name: 'payload_locked_documents_rels_media_fk',
    }).onDelete('cascade'),
    recipesIdFk: foreignKey({
      columns: [columns['recipesID']],
      foreignColumns: [recipes.id],
      name: 'payload_locked_documents_rels_recipes_fk',
    }).onDelete('cascade'),
    'recipes-prepIdFk': foreignKey({
      columns: [columns['recipes-prepID']],
      foreignColumns: [recipes_prep.id],
      name: 'payload_locked_documents_rels_recipes_prep_fk',
    }).onDelete('cascade'),
    'cocktail-recipesIdFk': foreignKey({
      columns: [columns['cocktail-recipesID']],
      foreignColumns: [cocktail_recipes.id],
      name: 'payload_locked_documents_rels_cocktail_recipes_fk',
    }).onDelete('cascade'),
    'cocktail-prep-itemsIdFk': foreignKey({
      columns: [columns['cocktail-prep-itemsID']],
      foreignColumns: [cocktail_prep_items.id],
      name: 'payload_locked_documents_rels_cocktail_prep_items_fk',
    }).onDelete('cascade'),
    'cocktail-batch-recipesIdFk': foreignKey({
      columns: [columns['cocktail-batch-recipesID']],
      foreignColumns: [cocktail_batch_recipes.id],
      name: 'payload_locked_documents_rels_cocktail_batch_recipes_fk',
    }).onDelete('cascade'),
  }),
)

export const payload_preferences = pgTable(
  'payload_preferences',
  {
    id: serial('id').primaryKey(),
    key: varchar('key'),
    value: jsonb('value'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => ({
    payload_preferences_key_idx: index('payload_preferences_key_idx').on(columns.key),
    payload_preferences_updated_at_idx: index('payload_preferences_updated_at_idx').on(
      columns.updatedAt,
    ),
    payload_preferences_created_at_idx: index('payload_preferences_created_at_idx').on(
      columns.createdAt,
    ),
  }),
)

export const payload_preferences_rels = pgTable(
  'payload_preferences_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    usersID: integer('users_id'),
    appUsersID: integer('app_users_id'),
  },
  (columns) => ({
    order: index('payload_preferences_rels_order_idx').on(columns.order),
    parentIdx: index('payload_preferences_rels_parent_idx').on(columns.parent),
    pathIdx: index('payload_preferences_rels_path_idx').on(columns.path),
    payload_preferences_rels_users_id_idx: index('payload_preferences_rels_users_id_idx').on(
      columns.usersID,
    ),
    payload_preferences_rels_app_users_id_idx: index(
      'payload_preferences_rels_app_users_id_idx',
    ).on(columns.appUsersID),
    parentFk: foreignKey({
      columns: [columns['parent']],
      foreignColumns: [payload_preferences.id],
      name: 'payload_preferences_rels_parent_fk',
    }).onDelete('cascade'),
    usersIdFk: foreignKey({
      columns: [columns['usersID']],
      foreignColumns: [users.id],
      name: 'payload_preferences_rels_users_fk',
    }).onDelete('cascade'),
    appUsersIdFk: foreignKey({
      columns: [columns['appUsersID']],
      foreignColumns: [app_users.id],
      name: 'payload_preferences_rels_app_users_fk',
    }).onDelete('cascade'),
  }),
)

export const payload_migrations = pgTable(
  'payload_migrations',
  {
    id: serial('id').primaryKey(),
    name: varchar('name'),
    batch: numeric('batch'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => ({
    payload_migrations_updated_at_idx: index('payload_migrations_updated_at_idx').on(
      columns.updatedAt,
    ),
    payload_migrations_created_at_idx: index('payload_migrations_created_at_idx').on(
      columns.createdAt,
    ),
  }),
)

export const relations_users = relations(users, () => ({}))
export const relations_app_users_role = relations(app_users_role, ({ one }) => ({
  parent: one(app_users, {
    fields: [app_users_role.parent],
    references: [app_users.id],
    relationName: 'role',
  }),
}))
export const relations_app_users = relations(app_users, ({ many }) => ({
  role: many(app_users_role, {
    relationName: 'role',
  }),
}))
export const relations_media = relations(media, () => ({}))
export const relations_recipes_ingredients = relations(recipes_ingredients, ({ one }) => ({
  _parentID: one(recipes, {
    fields: [recipes_ingredients._parentID],
    references: [recipes.id],
    relationName: 'ingredients',
  }),
  linkedRecipe: one(recipes_prep, {
    fields: [recipes_ingredients.linkedRecipe],
    references: [recipes_prep.id],
    relationName: 'linkedRecipe',
  }),
}))
export const relations_recipes_category = relations(recipes_category, ({ one }) => ({
  parent: one(recipes, {
    fields: [recipes_category.parent],
    references: [recipes.id],
    relationName: 'category',
  }),
}))
export const relations_recipes_allergens = relations(recipes_allergens, ({ one }) => ({
  parent: one(recipes, {
    fields: [recipes_allergens.parent],
    references: [recipes.id],
    relationName: 'allergens',
  }),
}))
export const relations_recipes_images = relations(recipes_images, ({ one }) => ({
  _parentID: one(recipes, {
    fields: [recipes_images._parentID],
    references: [recipes.id],
    relationName: 'images',
  }),
  image: one(media, {
    fields: [recipes_images.image],
    references: [media.id],
    relationName: 'image',
  }),
}))
export const relations_recipes = relations(recipes, ({ many }) => ({
  ingredients: many(recipes_ingredients, {
    relationName: 'ingredients',
  }),
  category: many(recipes_category, {
    relationName: 'category',
  }),
  allergens: many(recipes_allergens, {
    relationName: 'allergens',
  }),
  images: many(recipes_images, {
    relationName: 'images',
  }),
}))
export const relations_recipes_prep_ingredients = relations(
  recipes_prep_ingredients,
  ({ one }) => ({
    _parentID: one(recipes_prep, {
      fields: [recipes_prep_ingredients._parentID],
      references: [recipes_prep.id],
      relationName: 'ingredients',
    }),
    linkedRecipe: one(recipes_prep, {
      fields: [recipes_prep_ingredients.linkedRecipe],
      references: [recipes_prep.id],
      relationName: 'linkedRecipe',
    }),
  }),
)
export const relations_recipes_prep_category = relations(recipes_prep_category, ({ one }) => ({
  parent: one(recipes_prep, {
    fields: [recipes_prep_category.parent],
    references: [recipes_prep.id],
    relationName: 'category',
  }),
}))
export const relations_recipes_prep_allergens = relations(recipes_prep_allergens, ({ one }) => ({
  parent: one(recipes_prep, {
    fields: [recipes_prep_allergens.parent],
    references: [recipes_prep.id],
    relationName: 'allergens',
  }),
}))
export const relations_recipes_prep_images = relations(recipes_prep_images, ({ one }) => ({
  _parentID: one(recipes_prep, {
    fields: [recipes_prep_images._parentID],
    references: [recipes_prep.id],
    relationName: 'images',
  }),
  image: one(media, {
    fields: [recipes_prep_images.image],
    references: [media.id],
    relationName: 'image',
  }),
}))
export const relations_recipes_prep = relations(recipes_prep, ({ many }) => ({
  ingredients: many(recipes_prep_ingredients, {
    relationName: 'ingredients',
  }),
  category: many(recipes_prep_category, {
    relationName: 'category',
  }),
  allergens: many(recipes_prep_allergens, {
    relationName: 'allergens',
  }),
  images: many(recipes_prep_images, {
    relationName: 'images',
  }),
}))
export const relations_cocktail_recipes_ingredients = relations(
  cocktail_recipes_ingredients,
  ({ one }) => ({
    _parentID: one(cocktail_recipes, {
      fields: [cocktail_recipes_ingredients._parentID],
      references: [cocktail_recipes.id],
      relationName: 'ingredients',
    }),
  }),
)
export const relations_cocktail_recipes_ingredients_full = relations(
  cocktail_recipes_ingredients_full,
  ({ one }) => ({
    _parentID: one(cocktail_recipes, {
      fields: [cocktail_recipes_ingredients_full._parentID],
      references: [cocktail_recipes.id],
      relationName: 'ingredients_full',
    }),
  }),
)
export const relations_cocktail_recipes_images = relations(cocktail_recipes_images, ({ one }) => ({
  _parentID: one(cocktail_recipes, {
    fields: [cocktail_recipes_images._parentID],
    references: [cocktail_recipes.id],
    relationName: 'images',
  }),
  image: one(media, {
    fields: [cocktail_recipes_images.image],
    references: [media.id],
    relationName: 'image',
  }),
}))
export const relations_cocktail_recipes_rels = relations(cocktail_recipes_rels, ({ one }) => ({
  parent: one(cocktail_recipes, {
    fields: [cocktail_recipes_rels.parent],
    references: [cocktail_recipes.id],
    relationName: '_rels',
  }),
  'cocktail-prep-itemsID': one(cocktail_prep_items, {
    fields: [cocktail_recipes_rels['cocktail-prep-itemsID']],
    references: [cocktail_prep_items.id],
    relationName: 'cocktail-prep-items',
  }),
  'cocktail-batch-recipesID': one(cocktail_batch_recipes, {
    fields: [cocktail_recipes_rels['cocktail-batch-recipesID']],
    references: [cocktail_batch_recipes.id],
    relationName: 'cocktail-batch-recipes',
  }),
}))
export const relations_cocktail_recipes = relations(cocktail_recipes, ({ many }) => ({
  ingredients: many(cocktail_recipes_ingredients, {
    relationName: 'ingredients',
  }),
  ingredients_full: many(cocktail_recipes_ingredients_full, {
    relationName: 'ingredients_full',
  }),
  images: many(cocktail_recipes_images, {
    relationName: 'images',
  }),
  _rels: many(cocktail_recipes_rels, {
    relationName: '_rels',
  }),
}))
export const relations_cocktail_prep_items_ingredients = relations(
  cocktail_prep_items_ingredients,
  ({ one }) => ({
    _parentID: one(cocktail_prep_items, {
      fields: [cocktail_prep_items_ingredients._parentID],
      references: [cocktail_prep_items.id],
      relationName: 'ingredients',
    }),
    linkedRecipe: one(cocktail_prep_items, {
      fields: [cocktail_prep_items_ingredients.linkedRecipe],
      references: [cocktail_prep_items.id],
      relationName: 'linkedRecipe',
    }),
  }),
)
export const relations_cocktail_prep_items_images = relations(
  cocktail_prep_items_images,
  ({ one }) => ({
    _parentID: one(cocktail_prep_items, {
      fields: [cocktail_prep_items_images._parentID],
      references: [cocktail_prep_items.id],
      relationName: 'images',
    }),
    image: one(media, {
      fields: [cocktail_prep_items_images.image],
      references: [media.id],
      relationName: 'image',
    }),
  }),
)
export const relations_cocktail_prep_items = relations(cocktail_prep_items, ({ many }) => ({
  ingredients: many(cocktail_prep_items_ingredients, {
    relationName: 'ingredients',
  }),
  images: many(cocktail_prep_items_images, {
    relationName: 'images',
  }),
}))
export const relations_cocktail_batch_recipes_ingredients = relations(
  cocktail_batch_recipes_ingredients,
  ({ one }) => ({
    _parentID: one(cocktail_batch_recipes, {
      fields: [cocktail_batch_recipes_ingredients._parentID],
      references: [cocktail_batch_recipes.id],
      relationName: 'ingredients',
    }),
    linkedRecipe: one(cocktail_prep_items, {
      fields: [cocktail_batch_recipes_ingredients.linkedRecipe],
      references: [cocktail_prep_items.id],
      relationName: 'linkedRecipe',
    }),
  }),
)
export const relations_cocktail_batch_recipes_images = relations(
  cocktail_batch_recipes_images,
  ({ one }) => ({
    _parentID: one(cocktail_batch_recipes, {
      fields: [cocktail_batch_recipes_images._parentID],
      references: [cocktail_batch_recipes.id],
      relationName: 'images',
    }),
    image: one(media, {
      fields: [cocktail_batch_recipes_images.image],
      references: [media.id],
      relationName: 'image',
    }),
  }),
)
export const relations_cocktail_batch_recipes = relations(cocktail_batch_recipes, ({ many }) => ({
  ingredients: many(cocktail_batch_recipes_ingredients, {
    relationName: 'ingredients',
  }),
  images: many(cocktail_batch_recipes_images, {
    relationName: 'images',
  }),
}))
export const relations_payload_locked_documents_rels = relations(
  payload_locked_documents_rels,
  ({ one }) => ({
    parent: one(payload_locked_documents, {
      fields: [payload_locked_documents_rels.parent],
      references: [payload_locked_documents.id],
      relationName: '_rels',
    }),
    usersID: one(users, {
      fields: [payload_locked_documents_rels.usersID],
      references: [users.id],
      relationName: 'users',
    }),
    appUsersID: one(app_users, {
      fields: [payload_locked_documents_rels.appUsersID],
      references: [app_users.id],
      relationName: 'appUsers',
    }),
    mediaID: one(media, {
      fields: [payload_locked_documents_rels.mediaID],
      references: [media.id],
      relationName: 'media',
    }),
    recipesID: one(recipes, {
      fields: [payload_locked_documents_rels.recipesID],
      references: [recipes.id],
      relationName: 'recipes',
    }),
    'recipes-prepID': one(recipes_prep, {
      fields: [payload_locked_documents_rels['recipes-prepID']],
      references: [recipes_prep.id],
      relationName: 'recipes-prep',
    }),
    'cocktail-recipesID': one(cocktail_recipes, {
      fields: [payload_locked_documents_rels['cocktail-recipesID']],
      references: [cocktail_recipes.id],
      relationName: 'cocktail-recipes',
    }),
    'cocktail-prep-itemsID': one(cocktail_prep_items, {
      fields: [payload_locked_documents_rels['cocktail-prep-itemsID']],
      references: [cocktail_prep_items.id],
      relationName: 'cocktail-prep-items',
    }),
    'cocktail-batch-recipesID': one(cocktail_batch_recipes, {
      fields: [payload_locked_documents_rels['cocktail-batch-recipesID']],
      references: [cocktail_batch_recipes.id],
      relationName: 'cocktail-batch-recipes',
    }),
  }),
)
export const relations_payload_locked_documents = relations(
  payload_locked_documents,
  ({ many }) => ({
    _rels: many(payload_locked_documents_rels, {
      relationName: '_rels',
    }),
  }),
)
export const relations_payload_preferences_rels = relations(
  payload_preferences_rels,
  ({ one }) => ({
    parent: one(payload_preferences, {
      fields: [payload_preferences_rels.parent],
      references: [payload_preferences.id],
      relationName: '_rels',
    }),
    usersID: one(users, {
      fields: [payload_preferences_rels.usersID],
      references: [users.id],
      relationName: 'users',
    }),
    appUsersID: one(app_users, {
      fields: [payload_preferences_rels.appUsersID],
      references: [app_users.id],
      relationName: 'appUsers',
    }),
  }),
)
export const relations_payload_preferences = relations(payload_preferences, ({ many }) => ({
  _rels: many(payload_preferences_rels, {
    relationName: '_rels',
  }),
}))
export const relations_payload_migrations = relations(payload_migrations, () => ({}))

type DatabaseSchema = {
  enum_app_users_role: typeof enum_app_users_role
  enum_recipes_ingredients_unit: typeof enum_recipes_ingredients_unit
  enum_recipes_category: typeof enum_recipes_category
  enum_recipes_allergens: typeof enum_recipes_allergens
  enum_recipes_prep_ingredients_unit: typeof enum_recipes_prep_ingredients_unit
  enum_recipes_prep_category: typeof enum_recipes_prep_category
  enum_recipes_prep_allergens: typeof enum_recipes_prep_allergens
  enum_recipes_prep_total_yield_unit: typeof enum_recipes_prep_total_yield_unit
  enum_cocktail_recipes_ingredients_unit: typeof enum_cocktail_recipes_ingredients_unit
  enum_cocktail_recipes_ingredients_full_unit: typeof enum_cocktail_recipes_ingredients_full_unit
  enum_cocktail_prep_items_ingredients_unit: typeof enum_cocktail_prep_items_ingredients_unit
  enum_cocktail_batch_recipes_ingredients_unit: typeof enum_cocktail_batch_recipes_ingredients_unit
  users: typeof users
  app_users_role: typeof app_users_role
  app_users: typeof app_users
  media: typeof media
  recipes_ingredients: typeof recipes_ingredients
  recipes_category: typeof recipes_category
  recipes_allergens: typeof recipes_allergens
  recipes_images: typeof recipes_images
  recipes: typeof recipes
  recipes_prep_ingredients: typeof recipes_prep_ingredients
  recipes_prep_category: typeof recipes_prep_category
  recipes_prep_allergens: typeof recipes_prep_allergens
  recipes_prep_images: typeof recipes_prep_images
  recipes_prep: typeof recipes_prep
  cocktail_recipes_ingredients: typeof cocktail_recipes_ingredients
  cocktail_recipes_ingredients_full: typeof cocktail_recipes_ingredients_full
  cocktail_recipes_images: typeof cocktail_recipes_images
  cocktail_recipes: typeof cocktail_recipes
  cocktail_recipes_rels: typeof cocktail_recipes_rels
  cocktail_prep_items_ingredients: typeof cocktail_prep_items_ingredients
  cocktail_prep_items_images: typeof cocktail_prep_items_images
  cocktail_prep_items: typeof cocktail_prep_items
  cocktail_batch_recipes_ingredients: typeof cocktail_batch_recipes_ingredients
  cocktail_batch_recipes_images: typeof cocktail_batch_recipes_images
  cocktail_batch_recipes: typeof cocktail_batch_recipes
  payload_locked_documents: typeof payload_locked_documents
  payload_locked_documents_rels: typeof payload_locked_documents_rels
  payload_preferences: typeof payload_preferences
  payload_preferences_rels: typeof payload_preferences_rels
  payload_migrations: typeof payload_migrations
  relations_users: typeof relations_users
  relations_app_users_role: typeof relations_app_users_role
  relations_app_users: typeof relations_app_users
  relations_media: typeof relations_media
  relations_recipes_ingredients: typeof relations_recipes_ingredients
  relations_recipes_category: typeof relations_recipes_category
  relations_recipes_allergens: typeof relations_recipes_allergens
  relations_recipes_images: typeof relations_recipes_images
  relations_recipes: typeof relations_recipes
  relations_recipes_prep_ingredients: typeof relations_recipes_prep_ingredients
  relations_recipes_prep_category: typeof relations_recipes_prep_category
  relations_recipes_prep_allergens: typeof relations_recipes_prep_allergens
  relations_recipes_prep_images: typeof relations_recipes_prep_images
  relations_recipes_prep: typeof relations_recipes_prep
  relations_cocktail_recipes_ingredients: typeof relations_cocktail_recipes_ingredients
  relations_cocktail_recipes_ingredients_full: typeof relations_cocktail_recipes_ingredients_full
  relations_cocktail_recipes_images: typeof relations_cocktail_recipes_images
  relations_cocktail_recipes_rels: typeof relations_cocktail_recipes_rels
  relations_cocktail_recipes: typeof relations_cocktail_recipes
  relations_cocktail_prep_items_ingredients: typeof relations_cocktail_prep_items_ingredients
  relations_cocktail_prep_items_images: typeof relations_cocktail_prep_items_images
  relations_cocktail_prep_items: typeof relations_cocktail_prep_items
  relations_cocktail_batch_recipes_ingredients: typeof relations_cocktail_batch_recipes_ingredients
  relations_cocktail_batch_recipes_images: typeof relations_cocktail_batch_recipes_images
  relations_cocktail_batch_recipes: typeof relations_cocktail_batch_recipes
  relations_payload_locked_documents_rels: typeof relations_payload_locked_documents_rels
  relations_payload_locked_documents: typeof relations_payload_locked_documents
  relations_payload_preferences_rels: typeof relations_payload_preferences_rels
  relations_payload_preferences: typeof relations_payload_preferences
  relations_payload_migrations: typeof relations_payload_migrations
}

declare module '@payloadcms/db-postgres' {
  export interface GeneratedDatabaseSchema {
    schema: DatabaseSchema
  }
}
