/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
    appUsers: AppUserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    appUsers: AppUser;
    media: Media;
    recipes: Recipe;
    'recipes-prep': RecipesPrep;
    'cocktail-recipes': CocktailRecipe;
    'cocktail-prep-items': CocktailPrepItem;
    'cocktail-batch-recipes': CocktailBatchRecipe;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    appUsers: AppUsersSelect<false> | AppUsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    recipes: RecipesSelect<false> | RecipesSelect<true>;
    'recipes-prep': RecipesPrepSelect<false> | RecipesPrepSelect<true>;
    'cocktail-recipes': CocktailRecipesSelect<false> | CocktailRecipesSelect<true>;
    'cocktail-prep-items': CocktailPrepItemsSelect<false> | CocktailPrepItemsSelect<true>;
    'cocktail-batch-recipes': CocktailBatchRecipesSelect<false> | CocktailBatchRecipesSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  globals: {};
  globalsSelect: {};
  locale: null;
  user:
    | (User & {
        collection: 'users';
      })
    | (AppUser & {
        collection: 'appUsers';
      });
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface AppUserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "appUsers".
 */
export interface AppUser {
  id: number;
  name: string;
  role: ('foh' | 'boh' | 'bartender' | 'admin')[];
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "recipes".
 */
export interface Recipe {
  id: number;
  name: string;
  method?: string | null;
  plateBuild?: string | null;
  ingredients?:
    | {
        ingredient: string;
        unit:
          | 'gr'
          | 'g'
          | 'oz'
          | 'ea'
          | 'lbs'
          | 'kg'
          | 'ml'
          | 'l'
          | 'tsp'
          | 'gal'
          | 'tbsp'
          | 'cup'
          | 'pcs'
          | 'pc'
          | 'qt'
          | 'tt'
          | 'bag'
          | 'case'
          | 'box'
          | 'portion'
          | 'hotel pan'
          | 'order'
          | 'pastry bags'
          | 'hp'
          | 'block';
        qty?: number | null;
        'cuts-prep-brand'?: string | null;
        isSubRecipe?: boolean | null;
        linkedRecipe?: (number | null) | RecipesPrep;
        id?: string | null;
      }[]
    | null;
  implemented?: string | null;
  lastRevised?: string | null;
  prepTime?: string | null;
  kitchen?: string | null;
  stations?: string | null;
  mealPeriod?: string | null;
  mealType?: string | null;
  platingInstructions?: string | null;
  plateType?: string | null;
  utensils?: string | null;
  category?: ('' | 'dinner' | 'brunch')[] | null;
  allergens?:
    | (
        | 'alcohol'
        | 'allium'
        | 'anchovy'
        | 'ancient_grains'
        | 'black_pepper'
        | 'capsaicin'
        | 'cilantro'
        | 'cinnamon'
        | 'citrus'
        | 'dairy'
        | 'eggs'
        | 'fish'
        | 'fish_roe'
        | 'fryer_cc_issues'
        | 'garlic'
        | 'ginger'
        | 'gluten'
        | 'honey'
        | 'msg'
        | 'mollusk'
        | 'mushroom'
        | 'mustard'
        | 'nightshade'
        | 'onion'
        | 'peanuts'
        | 'pineapple'
        | 'pork'
        | 'seafood'
        | 'sesame'
        | 'shellfish'
        | 'soy'
        | 'stonefruit'
        | 'sulfites'
        | 'tree_nuts'
        | 'wheat'
      )[]
    | null;
  images?:
    | {
        image: number | Media;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "recipes-prep".
 */
export interface RecipesPrep {
  id: number;
  name: string;
  dishes?: string | null;
  method?: string | null;
  ingredients?:
    | {
        ingredient: string;
        unit:
          | 'gr'
          | 'g'
          | 'oz'
          | 'ea'
          | 'lbs'
          | 'kg'
          | 'ml'
          | 'l'
          | 'tsp'
          | 'gal'
          | 'tbsp'
          | 'cup'
          | 'pcs'
          | 'pc'
          | 'qt'
          | 'tt'
          | 'bag'
          | 'case'
          | 'box'
          | 'portion'
          | 'hotel pan'
          | 'order'
          | 'pastry bags'
          | 'hp'
          | 'block';
        qty?: number | null;
        'cuts-prep-brand'?: string | null;
        isSubRecipe?: boolean | null;
        linkedRecipe?: (number | null) | RecipesPrep;
        id?: string | null;
      }[]
    | null;
  category?: ('' | 'dinner' | 'brunch')[] | null;
  prepTime?: string | null;
  shelfLife?: string | null;
  stations?: string | null;
  equipment?: string | null;
  kitchenTools?: string | null;
  totalYield?: {
    qty?: number | null;
    unit?:
      | (
          | 'gr'
          | 'g'
          | 'oz'
          | 'ea'
          | 'lbs'
          | 'kg'
          | 'ml'
          | 'l'
          | 'tsp'
          | 'gal'
          | 'tbsp'
          | 'cup'
          | 'pcs'
          | 'pc'
          | 'qt'
          | 'tt'
          | 'bag'
          | 'case'
          | 'box'
          | 'portion'
          | 'hotel pan'
          | 'order'
          | 'pastry bags'
          | 'hp'
          | 'block'
        )
      | null;
  };
  allergens?:
    | (
        | 'alcohol'
        | 'allium'
        | 'anchovy'
        | 'ancient_grains'
        | 'black_pepper'
        | 'capsaicin'
        | 'cilantro'
        | 'cinnamon'
        | 'citrus'
        | 'dairy'
        | 'eggs'
        | 'fish'
        | 'fish_roe'
        | 'fryer_cc_issues'
        | 'garlic'
        | 'ginger'
        | 'gluten'
        | 'honey'
        | 'msg'
        | 'mollusk'
        | 'mushroom'
        | 'mustard'
        | 'nightshade'
        | 'onion'
        | 'peanuts'
        | 'pineapple'
        | 'pork'
        | 'seafood'
        | 'sesame'
        | 'shellfish'
        | 'soy'
        | 'stonefruit'
        | 'sulfites'
        | 'tree_nuts'
        | 'wheat'
      )[]
    | null;
  images?:
    | {
        image: number | Media;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cocktail-recipes".
 */
export interface CocktailRecipe {
  id: number;
  name: string;
  method?: string | null;
  ingredients?:
    | {
        ingredient: string;
        unit: '' | 'oz' | 'ml' | 'dash' | 'tsp' | 'tbsp' | 'g' | 'drop' | 'splash' | 'ea';
        qty: number;
        isSubRecipe?: boolean | null;
        linkedRecipe?:
          | ({
              relationTo: 'cocktail-prep-items';
              value: number | CocktailPrepItem;
            } | null)
          | ({
              relationTo: 'cocktail-batch-recipes';
              value: number | CocktailBatchRecipe;
            } | null);
        id?: string | null;
      }[]
    | null;
  ingredients_full?:
    | {
        ingredient: string;
        unit: '' | 'oz' | 'ml' | 'dash' | 'tsp' | 'tbsp' | 'g' | 'drop' | 'splash' | 'ea';
        qty: number;
        isSubRecipe?: boolean | null;
        linkedRecipe?:
          | ({
              relationTo: 'cocktail-prep-items';
              value: number | CocktailPrepItem;
            } | null)
          | ({
              relationTo: 'cocktail-batch-recipes';
              value: number | CocktailBatchRecipe;
            } | null);
        id?: string | null;
      }[]
    | null;
  allergens?:
    | (
        | 'alcohol'
        | 'allium'
        | 'anchovy'
        | 'ancient_grains'
        | 'black_pepper'
        | 'capsaicin'
        | 'cilantro'
        | 'cinnamon'
        | 'citrus'
        | 'dairy'
        | 'eggs'
        | 'fish'
        | 'fish_roe'
        | 'fryer_cc_issues'
        | 'garlic'
        | 'ginger'
        | 'gluten'
        | 'honey'
        | 'msg'
        | 'mollusk'
        | 'mushroom'
        | 'mustard'
        | 'nightshade'
        | 'onion'
        | 'peanuts'
        | 'pineapple'
        | 'pork'
        | 'seafood'
        | 'sesame'
        | 'shellfish'
        | 'soy'
        | 'stonefruit'
        | 'sulfites'
        | 'tree_nuts'
        | 'wheat'
      )[]
    | null;
  yield?: string | null;
  ice?: string | null;
  garnish?: string | null;
  glassware?: string | null;
  description?: string | null;
  images?:
    | {
        image: number | Media;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cocktail-prep-items".
 */
export interface CocktailPrepItem {
  id: number;
  name: string;
  method?: string | null;
  ingredients?:
    | {
        ingredient: string;
        unit: 'g' | 'kg' | 'ml' | 'l' | 'tsp' | 'tbsp' | 'cup' | 'pcs' | 'ea' | 'quart';
        qty: number;
        isSubRecipe?: boolean | null;
        linkedRecipe?: (number | null) | CocktailPrepItem;
        id?: string | null;
      }[]
    | null;
  yield?: string | null;
  images?:
    | {
        image: number | Media;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cocktail-batch-recipes".
 */
export interface CocktailBatchRecipe {
  id: number;
  name: string;
  method?: string | null;
  ingredients?:
    | {
        ingredient: string;
        unit: 'g' | 'kg' | 'ml' | 'l' | 'tsp' | 'tbsp' | 'cup' | 'pcs' | 'ea';
        qty: number;
        isSubRecipe?: boolean | null;
        linkedRecipe?: (number | null) | CocktailPrepItem;
        id?: string | null;
      }[]
    | null;
  yield?: string | null;
  images?:
    | {
        image: number | Media;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'appUsers';
        value: number | AppUser;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'recipes';
        value: number | Recipe;
      } | null)
    | ({
        relationTo: 'recipes-prep';
        value: number | RecipesPrep;
      } | null)
    | ({
        relationTo: 'cocktail-recipes';
        value: number | CocktailRecipe;
      } | null)
    | ({
        relationTo: 'cocktail-prep-items';
        value: number | CocktailPrepItem;
      } | null)
    | ({
        relationTo: 'cocktail-batch-recipes';
        value: number | CocktailBatchRecipe;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'appUsers';
        value: number | AppUser;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'appUsers';
        value: number | AppUser;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "appUsers_select".
 */
export interface AppUsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "recipes_select".
 */
export interface RecipesSelect<T extends boolean = true> {
  name?: T;
  method?: T;
  plateBuild?: T;
  ingredients?:
    | T
    | {
        ingredient?: T;
        unit?: T;
        qty?: T;
        'cuts-prep-brand'?: T;
        isSubRecipe?: T;
        linkedRecipe?: T;
        id?: T;
      };
  implemented?: T;
  lastRevised?: T;
  prepTime?: T;
  kitchen?: T;
  stations?: T;
  mealPeriod?: T;
  mealType?: T;
  platingInstructions?: T;
  plateType?: T;
  utensils?: T;
  category?: T;
  allergens?: T;
  images?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "recipes-prep_select".
 */
export interface RecipesPrepSelect<T extends boolean = true> {
  name?: T;
  dishes?: T;
  method?: T;
  ingredients?:
    | T
    | {
        ingredient?: T;
        unit?: T;
        qty?: T;
        'cuts-prep-brand'?: T;
        isSubRecipe?: T;
        linkedRecipe?: T;
        id?: T;
      };
  category?: T;
  prepTime?: T;
  shelfLife?: T;
  stations?: T;
  equipment?: T;
  kitchenTools?: T;
  totalYield?:
    | T
    | {
        qty?: T;
        unit?: T;
      };
  allergens?: T;
  images?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cocktail-recipes_select".
 */
export interface CocktailRecipesSelect<T extends boolean = true> {
  name?: T;
  method?: T;
  ingredients?:
    | T
    | {
        ingredient?: T;
        unit?: T;
        qty?: T;
        isSubRecipe?: T;
        linkedRecipe?: T;
        id?: T;
      };
  ingredients_full?:
    | T
    | {
        ingredient?: T;
        unit?: T;
        qty?: T;
        isSubRecipe?: T;
        linkedRecipe?: T;
        id?: T;
      };
  allergens?: T;
  yield?: T;
  ice?: T;
  garnish?: T;
  glassware?: T;
  description?: T;
  images?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cocktail-prep-items_select".
 */
export interface CocktailPrepItemsSelect<T extends boolean = true> {
  name?: T;
  method?: T;
  ingredients?:
    | T
    | {
        ingredient?: T;
        unit?: T;
        qty?: T;
        isSubRecipe?: T;
        linkedRecipe?: T;
        id?: T;
      };
  yield?: T;
  images?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cocktail-batch-recipes_select".
 */
export interface CocktailBatchRecipesSelect<T extends boolean = true> {
  name?: T;
  method?: T;
  ingredients?:
    | T
    | {
        ingredient?: T;
        unit?: T;
        qty?: T;
        isSubRecipe?: T;
        linkedRecipe?: T;
        id?: T;
      };
  yield?: T;
  images?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}